require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - '*.gemspec'
    - 'Gemfile'
    - vendor/bundle/ruby/**/*

RSpec/NotToNot:
  SupportedStyles: to_not
  # disable because an error is being raised
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Lambda:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/ClassCheck:
  Enabled: false
  # we don't care about kind_of? vs is_a?

Style/StringLiterals:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

# Github's PR width is 120 characters
Layout/LineLength:
  Max: 120
  AllowURI: true
  Exclude:
    - spec/**/*

# Align with the style guide, we don't prefer anything
Style/CollectionMethods:
  Enabled: false

Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: true
  Max: 30

Metrics/BlockLength:
  Max: 25
  AllowedMethods:
    - context
    - describe
    - define

Rails/RakeEnvironment:
  Exclude:
    - 'Rakefile'

Rails/ApplicationJob:
  Exclude:
    - 'lib/webhook_system/job.rb'

Rails/ApplicationRecord:
  Exclude:
    - 'lib/webhook_system/event_log.rb'
    - 'lib/webhook_system/subscription.rb'
    - 'lib/webhook_system/subscription_topic.rb'
